zsh: Totally redo zsh and remove so many old things
Basically remove all of the scripts and startup files because they were
totally unneeded. Most of the ZSH config is in the zshrc now, with the
exception of a few functions.

I want to try to minimize the amount of functions in my main zshrc
because it looks junky and most of the time is only used once. This is
essentially a util, hence the new utils directory.

The prompt is totally redone too because I started noticing performance
issues on bad computers (raspberry pis').

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,25 +1,105 @@
+# Global array
+
 typeset -A _ramen
+_ramen[ZSH_HOME]="$HOME/.zsh"
 
-# Configure this repo with the ramen typeset
-_ramen[zsh_dir]="$HOME/.zsh"
-_ramen[color_env]='256'
-_ramen[vim_lite]='false'
+# Inlcude plugins and utils
+source $_ramen[ZSH_HOME]/utils/colors.zsh
+source $_ramen[ZSH_HOME]/utils/time.zsh
+source $_ramen[ZSH_HOME]/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
 
-# Local overrides
-LOCAL_RC=$ZDOTDIR/.zshrc.local
-test -f $LOCAL_RC && source $LOCAL_RC
+# Aliases
 
-include() { [[ -f "$1" ]] && source "$1" }
+alias v='vim'
+alias vi='vim'
+alias l='ls'
+alias cp='cp-v'
+alias man='nocorrect man'
+alias mkdir='nocorrect mkdir'
+alias mv='nocorrect mv'
+alias sudo='nocorrect sudo'
+alias docker='nocorrect docker'
 
-# Config Files
-function () {
-  local zsh_source_files=$(find $_ramen[zsh_dir]/startup/*.zsh -maxdepth 1 -type l ! -iname "binds.zsh")
-  for (( i=1;i<=$(echo "$zsh_source_files" | wc -l);i++ )); do
-    include $(echo "$zsh_source_files" | awk NR==$i)
-  done
-  include $_ramen[zsh_dir]/startup/binds.zsh 2>/dev/null
+if [ "$(uname 2> /dev/null)" = "Linux" ]; then
+  alias ls='ls --color=always --group-directories'
+  alias ll='ls -la --color=always --group-directories'
+fi
+
+# Binds
+
+bindkey -e
+bindkey '^w' forward-word
+bindkey '^b' backward-word
+bindkey '^d' kill-whole-line
+bindkey '^k' backward-kill-word
+bindkey '^j' kill-word
+
+# Completion
+
+autoload -Uz compinit
+autoload -U +X bashcompinit && bashcompinit
+compinit
+
+zstyle ':completion:*' auto-description 'specify: %d'
+zstyle ':completion:*' completer _expand _complete _correct _approximate
+zstyle ':completion:*' format ''
+zstyle ':completion:*' group-name ''
+zstyle ':completion:*' menu select=2
+zstyle ':completion:*' list-colors ''
+zstyle ':completion:*' list-prompt %SList: %p%s
+zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
+zstyle ':completion:*' menu select
+zstyle ':completion:*' select-prompt %SList: %p%s
+zstyle ':completion:*' use-compctl false
+zstyle ':completion:*' verbose true
+zstyle ':completion:*:history-words' stop yes
+zstyle ':completion:*:history-words' remove-all-dups yes
+zstyle ':completion:*:history-words' list false
+zstyle ':completion:*:history-words' menu yes
+zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
+zstyle ':completion:*:*kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
+
+# Options
+
+setopt prompt_subst
+setopt promptsubst
+setopt append_history
+setopt extended_history
+setopt sharehistory
+setopt hist_reduce_blanks
+setopt always_to_end
+setopt complete_in_word
+setopt auto_menu
+setopt correct
+setopt correctall
+setopt noflowcontrol
+setopt hist_verify
+setopt list_packed
+
+# Prompt
+function preexec {
+  timer=${timer:-$SECONDS}
+  export ZSH_COMMAND_TIME=""
 }
 
-# Plugins
-include $_ramen[zsh_dir]/plugins/zsh-autopair/autopair.plugin.zsh
-include $_ramen[zsh_dir]/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
+function precmd {
+  _ramen[EXIT_CODE]=$?
+
+  if [ $timer ]; then
+    _ramen[COMMAND_TIME]=$(($SECONDS - $timer))
+    export ZSH_COMMAND_TIME="$_ramen[COMMAND_TIME]"
+    zsh_command_time
+    unset timer
+  fi
+
+  local USER="@$_ramen[YELLOW]%n"
+  local DIR="$_ramen[BLUE]%~"
+
+  # Paint USER red if command fails
+  [ ! $_ramen[EXIT_CODE] -eq 0 ] && local USER="$_ramen[RED]%n"
+
+  PROMPT="$_ramen[BOLD_START]$USER$_ramen[WHITE]:$DIR$_ramen[WHITE]$_ramen[BOLD_END]%# "
+  RPROMPT="$_ramen[GRAY]$_ramen[COMMAND_TIME]$_ramen[WHITE]"
+}
+
+export SPROMPT="%B%F{red}'%R'%b%f -> %B%F{red}'%r'%b%f [%B%Uy%u%bes, %B%Un%u%bo, %B%Ue%u%bdit, %B%Ua%u%bbort]? "
